# Generated by Django 4.1.7 on 2023-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='content',
            field=models.CharField(max_length=2083, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='link',
            field=models.CharField(default='', max_length=2083, unique=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='price',
            field=models.CharField(max_length=200, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=200, verbose_name='марка авто'),
        ),
    ]
