# Generated by Django 4.1.7 on 2023-03-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_alter_tasks_content_alter_tasks_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Note',
        ),
    ]
