# Generated by Django 4.1.7 on 2023-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_rename_tasks_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='link',
            field=models.CharField(max_length=2083, verbose_name='ссылка'),
        ),
    ]
